name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Explicitly define permissions at workflow level
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for git operations

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci # Using ci instead of install for cleaner, more reliable builds

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true # Automatically remove deleted files from the deployment
          single-commit: true # Maintain only the latest commit on gh-pages branch
          token: ${{ secrets.GITHUB_TOKEN }}
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com 